"""create risk assessments table

Revision ID: 72f91d3c8b90
Revises: b7211f0954a1
Create Date: 2026-07-25 18:05:47.444921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f91d3c8b90'
down_revision: Union[str, Sequence[str], None] = 'b7211f0954a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_reading_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('temperature_risk', sa.Float(), nullable=False),
    sa.Column('humidity_risk', sa.Float(), nullable=False),
    sa.Column('smoke_risk', sa.Float(), nullable=False),
    sa.Column('gas_risk', sa.Float(), nullable=False),
    sa.Column('water_risk', sa.Float(), nullable=False),
    sa.Column('vibration_risk', sa.Float(), nullable=False),
    sa.Column('flame_risk', sa.Float(), nullable=False),
    sa.Column('occupancy_risk', sa.Float(), nullable=False),
    sa.Column('battery_risk', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_reading_id'], ['sensor_readings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_level'), 'risk_assessments', ['level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_sensor_reading_id'), 'risk_assessments', ['sensor_reading_id'], unique=True)
    op.create_index(op.f('ix_risk_assessments_zone_id'), 'risk_assessments', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_zone_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_sensor_reading_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_level'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
