"""create sensor readings table

Revision ID: b7211f0954a1
Revises: bab1f0c2701a
Create Date: 2026-07-25 14:50:17.892482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7211f0954a1'
down_revision: Union[str, Sequence[str], None] = 'bab1f0c2701a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('smoke_ppm', sa.Float(), nullable=True),
    sa.Column('gas_ppm', sa.Float(), nullable=True),
    sa.Column('water_level_percent', sa.Float(), nullable=True),
    sa.Column('vibration_level', sa.Float(), nullable=True),
    sa.Column('flame_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('motion_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('occupancy_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_device_id'), 'sensor_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_zone_id'), 'sensor_readings', ['zone_id'], unique=False)
    op.create_index('ix_sensor_readings_zone_received', 'sensor_readings', ['zone_id', 'received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensor_readings_zone_received', table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_zone_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_device_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###
